% TM1_findHeelStrikes
global homepath subject F p
tic
for subj = 1:subject.n
    for blk = 1:length(subject.blockname)
    [F{subj}.hsR{blk},F{subj}.hsL{blk},F{subj}.toR{blk},F{subj}.toL{blk}] =...
        getHeelStrikeForce(F{subj}.R{blk},F{subj}.L{blk},F{subj}.time{blk});
    % get indices
     [F{subj}.hsR_idx{blk},F{subj}.hsL_idx{blk},F{subj}.toR_idx{blk},F{subj}.toL_idx{blk}] =...
        getHeelStrikeForce_index(F{subj}.R{blk},F{subj}.L{blk},F{subj}.time{blk});
    
%     [p{subj}.tlaR{blk},p{subj}.tlaL{blk}] = getTrailingLimbAngle(p{subj}.Rankle{blk},...
%         p{subj}.Lankle{blk}, p{subj}.Rpsis{blk}, p{subj}.Lpsis{blk},...
%         p{subj}.trajtime{blk});
    [p{subj}.hsR{blk},p{subj}.hsL{blk},p{subj}.toR{blk},p{subj}.toL{blk}] =...
        getHeelStrikeMarker(p{subj}.Rtoe{blk},p{subj}.Ltoe{blk},...
        p{subj}.Rheel{blk},p{subj}.Lheel{blk},p{subj}.trajtime{blk});
%     [p{subj}.hsR{blk},p{subj}.hsL{blk},p{subj}.toR{blk},p{subj}.toL{blk}] =...
%         getHeelStrikeAnkleMarker(p{subj}.Rankle{blk},p{subj}.Lankle{blk},...
%         p{subj}.trajtime{blk});
    end
end
toc