%% TM01_
clear all
close all

global subject homepath colors
homepath = pwd;
colors.high = [248,118,102]/255; % coral-ly orange
colors.low = [75,143,140]/255; %teal-y
% take the mat files for each subject and build a full structure, so that
% we can loop through subjects
subject.list =  {'CBL' 'IHU' 'EDC' 'DCD'...
    'TLM' 'ONN' 'MRU' 'UKG'...
    'TSC'}; % 'DAT' %{'DCD'}; %
subject.order = [1 2 3 4;...
    1 2 3 4;...
    3 4 1 2;...
    3 4 1 2;...
    1 2 3 4;...
    1 2 3 4;...
    3 4 1 2;...
    3 4 1 2;...
    1 2 3 4]; 
% this refers to the block numbers in HEL HES LEL LES order
subject.fastleg = [1 1 1 1;...
    2 2 2 2;...
    2 2 2 2;...
    1 1 2 2;...
    2 2 2 2;...
    1 1 1 1;...
    2 2 2 2;...
    1 1 1 1;...
    1 1 2 2];
% this refers to the fast leg in each block; right is 1 and left is 2
subject.n = length(subject.list);
subject.leglabel = {'right' 'left'};
subject.effortlabel = {'high effort learning', 'high effort savings' 'low effort learning' 'low effort savings'};
subject.blockname = {'HE1' 'HE2' 'LE1' 'LE2'};
subject.nblk = length(subject.blockname);

for subj = 1:subject.n
    file_force = [subject.list{subj} '_F.mat'];
    file_marker = [subject.list{subj} '_p.mat'];
    cd('C:\Users\rache\OneDrive\Documents\GitHub\Treadmill\viconmatlab_starter\matData')
    a = load(file_force);
    b = load(file_marker);
    F{subj} = a.f;
    p{subj} = b.pp;
end
cd(homepath)
clearvars -except F p subject homepath colors